name = "Create Explore Modpack"
author = "lowgain"
version = "0.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f436e4f79fb4867ad17c036ee83713a436fdd9be5bf5b24d5d6b1636f4b94067"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
